version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../docker/.env

  web:
    build:
      context: ..
      dockerfile: /docker/dockerfiles/DockerfileAdmin
      args:
        - --no-cache
    container_name: web
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../standupuz_web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../standupuz_web/.env


  bot:
    build:
      context: ..
      dockerfile: /docker/dockerfiles/DockerfileBot
      args:
        - --no-cache
    container_name: bot
    volumes:
      - ../bot:/app
    depends_on:
      - db
    env_file:
      - ../bot/.env


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value:

